### ISSUE TITLE
Multistage docker builds

### ISSUE THREAD

**Issue by nstogner** [windmilleng/tiltdemo#8]
Multistage docker builds for Go are considered best practice. Typically the destination image does not contain the Go SDK. This example includes single stage Dockerfiles... Does this mean one should maintain two Dockerfiles (dev & prod) when taking advantage of Tilt's live update functionality?

**Comment by nicks** [comment]
Good question! There's two common setups we see:

1) You include the entire go toolchain in your destination image, so that Tilt can do the live-update in-image.

2) You cross-compile the Go static binary, and then copy the static binary into the image

(1) is the easiest to get started with, which you can see in this example. If you use a multi-stage docker build, you can tell Tilt to do `docker_build(target='the-target-with-the-go-toolchain')` to get the right stage.

(2) takes a bit more expertise. Here's a good project that demonstrates a static binary approach for building Docker images: https://github.com/thockin/go-build-template

To do this with Tilt, you create a [local_resource](https://docs.tilt.dev/local_resource.html) that compiles the static binary, and use live_update to sync the static binary into the container.

Hope that helps! It can be a bit hard to get your head around the different options and trade-offs involved; it depends a lot on how you're willing to trade complexity for a faster dev loop.

**Comment by suzaku** [comment]
Does this mean that I need to use a separate `Dockerfile` for Tilt development?

**Comment by nicks** [comment]
we now have an official Go guide, that shows best practices for Tilt with Go
https://docs.tilt.dev/example_go.html
The approach described there should work with multi-stage dockerfiles.

It might make sense to delete this repo
